config/routes.rb
Tweet2review::Application.routes.draw do

  match '/movies/:id/:action/:page' => 'movies'

  resources :movies do

    collection do
      get :autocomplete
    end

    member do
      get :closest
      get :sync
      get :positive
      get :negative
      get :mixed
      get :fresh
      get :terminate
      get :spotlight
      get :edit_positive
      get :edit_negative
      get :edit_mixed
      get :edit_fresh
      get :edit_external
      get :edit_spotlight
      get :edit_terminate
    end
    resources :keywords
  end

  resources :keywords

  match '/media(/:dragonfly)', :to => Dragonfly[:images]

  match 'login' =>   'application#login'

  match 'logout' =>  'application#logout'

  root :to => "movies#index"
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  geocode_ip_address

  before_filter :authenticate, :except => [:autocomplete, :index, :show, :positive, :negative, :mixed, :closest]

  #caches_page   :index, :show
  #cache_sweeper :movie_sweeper, :only => [:update, :create]
  #caches_action :show, :if => proc { params[:page].blank? }
  def closest
    @movie = Movie.find(params[:id].to_i)
    res = Geokit::Geocoders::GoogleGeocoder.reverse_geocode(params.values_at(:lat,:lng))
    @theaters = Scrapper.new(open(MovieFinder.new(@movie.name, res.zip).today)).to_theaters
    render :json => @theaters.to_json
  end


  def autocomplete
    movies = Movie.where(["movies.name like ?","%#{params[:term]}%"]).to_ary
    render :json => movies.inject([]) { |a,m| a << { :label => m.name, :url => movie_path(m) } }
  end

  # GET /movies
  # GET /movies.xml
  def index
    @movies = Movie.active

    respond_to do |format|
      format.mobile
      format.html # index.html.erb
      format.xml  { render :xml => @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.xml
  def show
    puts session[:geo_location]
    @movie = Movie.find(params[:id].to_i)
    @tweets = @movie.tweets.assesed.paginate(:page => params[:page], :per_page => 21)
    respond_to do |format|
      format.mobile
      format.html # show.html.erb
    end
  end

  # GET /movies/new
  # GET /movies/new.xml
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id].to_i)
    @tweets = @movie.tweets.fresh.paginate(:page => params[:page])
  end

  # GET /movies/1/edit
  def sync
    @movie = Movie.find(params[:id].to_i).tap {|t| t.keywords.query_twitter }
    @tweets = @movie.tweets.paginate(:page => params[:page])
    render :action => 'edit'
  end

  %w(positive negative mixed spotlight fresh terminate external).each do |method|
    define_method(method) do
      @movie = Movie.find(params[:id].to_i)
      @tweets = @movie.tweets.send(method).paginate(:page => params[:page], :per_page => 21)
      respond_to do |format|
        format.mobile { render :action => :show }
        format.html { render :action => :show }
      end
    end

    define_method("edit_#{method}") do
      @movie  = Movie.find(params[:id].to_i)
      @search = @movie.tweets.send(method).search(params[:search])
      @tweets = @search.paginate(:page => params[:page])
      render :action => :admin
    end
  end


  # POST /movies
  # POST /movies.xml
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        expire_page :action => :index
        format.html { redirect_to(@movie, :notice => 'Movie was successfully created.') }
        format.xml  { render :xml => @movie, :status => :created, :location => @movie }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.xml
  def update
    @movie = Movie.find(params[:id].to_i)
    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        expire_page :action => :index
        format.html { redirect_to(@movie, :notice => 'Movie was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.xml
  def destroy
    @movie = Movie.find(params[:id].to_i)
    @movie.destroy
    expire_page :action => :index

    respond_to do |format|
      format.html { redirect_to(movies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def footer_link(title, url_options, options)
    options.update("data-icon" => "custom")
    if current_page?(url_options)
      options.update(:class => "ui-btn-active")
    end

    link_to title, url_for(url_options), options
  end
end

app/views/movies/_form.html.erb
<%= form_for(@movie,:html => {:multipart => true}) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:
      </h2>
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cover_image %><br />
    <%= f.file_field :cover_image %>
  </div>

  <div class="field">
    <%= f.label :released_on %><br />
    <%= f.date_select :released_on %>
  </div>

  <div class="field">
    <%= f.label :cast %><br />
    <%= f.text_field :cast %>
  </div>

  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>

  <div class="field">
    <%= f.label :producer %><br />
    <%= f.text_field :producer %>
  </div>

  <div class="field">
    <%= f.label :banner %><br />
    <%= f.text_field :banner %>
  </div>

  <div class="field">
    <%= f.label :music_director %><br />
    <%= f.text_field :music_director %>
  </div>

  <div class="field">
    <%= f.label :plot %><br />
    <%= f.text_area :plot %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="poster">
  <% if movie.cover_image %>
    <%= image_tag(movie.cover_image.thumb("300x225").url)  %>
  <% end %>
</div>

<div class="movie-info">
  <div class="movie-info-inner">
    <div class="movie-meta">
      <div class="title">
        <h3><%= movie.name %></h3>
      </div>
      <div class="credits">
        <span class="label">Starring: </span>
        <span class="content"><%= movie.cast %></span>
      </div>
      <div class="credits">
        <span class="label">Directed: </span>
        <span class="content"><%= movie.director %></span>
      </div>
      <div class="credits">
        <span class="label">Produced: </span>
        <span class="content"><%= movie.producer %></span>
      </div>
      <div class="credits">
        <span class="label">Released: </span>
        <span class="content"><%= movie.released_on.strftime("%d %B, %Y.") %></span>
      </div>
    </div>
    <div class="movie-score">
      <div class="percentage">
        <%= image_tag movie.computed_score.to_i > 50 ? "hit.png" : "flop.png" %>
        <%= movie.formatted_score %>
      </div>
      <p>
        <%= link_to "#{movie.tweets.positive.count} positive", positive_movie_path(movie) %> |
        <%= link_to "#{movie.tweets.negative.count} negative", negative_movie_path(movie) %> |
        <%= link_to "#{movie.tweets.mixed.count} mixed", mixed_movie_path(movie) %>
      </p>
    </div>
  </div>
</div>

app/views/movies/_movie.mobile.erb
<% if movie.cover_image %>
  <li>
    <%= image_tag movie.cover_image.thumb("80x80").url,:height => 80,:width => 80 %>
    <h2 style="margin-top:0;"><%= link_to movie.name, movie %> </h2>
    <p><strong><%= movie.computed_score %>%</strong></p>
    <p><%= movie.cast %></p>
  </li>
<% end %>

app/views/movies/admin.html.erb
<table border="1" class="edit-tweets">
  <tr>
    <th class="small-text"><%= sort_link @search, :created_on_twitter %></th>
    <th class="small-text"><%= sort_link @search, :from_user %></th>
    <th class="large-text"><%= sort_link @search, :text %></th>
    <th class="small-text">Category</th>
    <th class="small-text">Featured</th>
    <th class="small-text">Destroy</th>
  </tr>
  <%= form_for @search, :url => url_for(params.slice(:action,:controller,:id)) do |f| %>
    <tr>
      <td></td>
      <td class="small-text"><%= f.text_field :from_user_contains, :size => 15 %></td>
      <td><%= f.text_field :text_contains %></td>
      <td class="small-text">
        <% %w(positive negative mixed fresh terminate).each do | cat | %>
          <%= radio_button_tag "admin_category", cat , false, :class => 'category_all'%>
          <%= label_tag cat %>
          <br/>
        <% end %>
      </td>
      <td class="small-text"><input type="checkbox" id="feature_all"></td>
      <td class="small-text"><input type="checkbox" id="destroy_all"></td>
    </tr>
    <tr>
      <td colspan="6"><%= f.submit %></td>
    </tr>
  <% end %>

  <%= form_for(@movie,:html => {:multipart => true}) do |f| %>
    <% if @movie.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:
        </h2>
        <ul>
          <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.fields_for :tweets,@tweets do | tweet | %>
      <tr>
        <td class="small-text">
          <%= tweet.object.created_on_twitter %>
        </td>
        <td class="small-text">
          <%= tweet.object.from_user %>
        </td>
        <td class="large-text"><%= auto_link tweet.object.text, :urls, :target => :_blank %></td>
        <td class="small-text">
          <% %w(positive negative mixed fresh terminate).each do | cat | %>
            <%= tweet.radio_button :category, cat %>
            <%= f.label :category, cat.camelize %>
            <br/>
          <% end %>
        </td>
        <td class="small-text">
          <%= tweet.check_box :featured, {}, true,false %>
          <%= f.label :featured %>
        </td>
        <td class="small-text">
          <%= tweet.check_box :_destroy %>
          Delete: 
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="6">
        <%= f.submit %>
      </td>
    </tr>
  <% end %>
</table>

app/views/movies/closest.mobile.erb
<% content_for :title do %>
  <%= @movie.name %>
<% end %>
<%= image_tag(@movie.cover_image.thumb("300x225").url)  %>

<ul data-role="listview" data-inset="true"> 
  <% @theaters.each do | theater | %>
    <li> 
      <h3> <%= theater.name %> </h3> 
        <p><strong><%= theater.address %></strong></p> 
        <p class="ui-li-aside"><strong><%= theater.times %></strong></p> 
    </li> 
  <% end %>
</ul>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<% @movie.keywords.each do | keyword | %>
    <%= link_to keyword.name, keyword,  :confirm => 'Are you sure?', 
                                        :method => :delete, :class =>"tweet-link" %>
<% end %>

<%= form_for([@movie, @movie.keywords.new]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @movie, :class => 'tweet-link' %>  |
<%= link_to 'Search Twitter', sync_movie_path(@movie), :class => 'tweet-link' %> |
<%= link_to 'Back', movies_path, :class => 'tweet-link' %>  |

app/views/movies/index.html.erb
<% content_for :title do %>
  <%= "Review Umpire" %> 
<% end %>

<% content_for :description do %>
  <%= "Aggregates reviews of telugu movies." %> 
<% end %>

<% content_for :keywords do %>
  <%= "telugu movie reviews, telugu movie tweets" %> 
<% end %>

<ul id="nav">
  <% Movie.limit(13).to_ary.each do | movie | %>
    <% if movie.cover_image %>
      <li> <%= link_to image_tag(movie.cover_image.thumb("50x50").url, :width => 50, :height => 50), "#" %> </li>
    <% end %>
  <% end %>
</ul>

<div id="carousel">				
  <% Movie.limit(13).to_ary.each do | movie | %>
    <div>
      <%= render movie %>
      <%= render movie.tweets.spotlight.limit(8) %>
    </div>
  <% end %>
</div>

app/views/movies/index.mobile.erb
<% content_for :title do %>
  <h1>Review Umpire</h1>
<% end %>


<ul data-role="listview" data-filter="true">
  <% Movie.group(:released_on).select(:released_on).each do | date | %>
    <li data-role="list-divider"><%= date.released_on.strftime("%d %B, %Y") %></li>
    <%= render Movie.where(:released_on => date.released_on) %>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<% content_for :title do %>
  <%= "#{@movie.name} Review" %> 
<% end %>

<% content_for :description do %>
  <%= "Aggregates reviews of #{@movie.name}." %> 
<% end %>

<% content_for :keywords do %>
  <%= "#{@movie.name} movie reviews, #{@movie.name} tweets, #{@movie.name} talk, #{@movie.name} positive talk, #{@movie.name} negative talk" %> 
<% end %>
<%= render @movie %>
<div class="inner pager">
  <%= render :partial => "tweets/tweets", :locals => { :tweets => @tweets, :movie => @movie } %>
</div>

app/views/movies/show.mobile.erb
<% content_for :title do %>
  <h1><%= @movie.name %></h1>
<% end %>

<%= image_tag(@movie.cover_image.thumb("300x225").url)  %>

<ul class="showtimes" data-role="listview" data-inset="true" data-theme="c" data-url='<%= closest_movie_path(@movie) %>'>
  <li data-role="list-divider">Show times</li>
</ul>

<table>
  <tbody>
    <% @tweets.each do | tweet | %>
      <tr>
      <td> <%= image_tag tweet.profile_image_url, :height => 48, :width => 48, :class => "ui-thumb" %> </td>
        <td><%= tweet.text %></td>
    </tr>
    <% end %>
  </tbody>
</table>



<% content_for :menu do %>
<div data-role="navbar" data-theme="e" class="feelings">
  <ul> 
    <li>
      <%= footer_link "Love", { 
      :controller => "movies", :action => "positive" , :id => @movie.id 
      }, { :id => "love"} %>
    </li>
    <li>
      <%= footer_link "Hate", { 
      :controller => "movies", :action => "negative" , :id => @movie.id 
      }, { :id => "hate"} %>
    </li>
    <li>
      <%= footer_link "Mixed", { 
      :controller => "movies", :action => "mixed" , :id => @movie.id 
      }, { :id => "mixed"} %>
    </li>
  </ul> 
</div>
<% end %>