config/routes.rb
Tweet2review::Application.routes.draw do

  match '/movies/:id/:action/:page' => 'movies'

  resources :movies do

    collection do
      get :autocomplete
    end

    member do
      get :closest
      get :sync
      get :positive
      get :negative
      get :mixed
      get :fresh
      get :terminate
      get :spotlight
      get :edit_positive
      get :edit_negative
      get :edit_mixed
      get :edit_fresh
      get :edit_external
      get :edit_spotlight
      get :edit_terminate
    end
    resources :keywords
  end

  resources :keywords

  match '/media(/:dragonfly)', :to => Dragonfly[:images]

  match 'login' =>   'application#login'

  match 'logout' =>  'application#logout'

  root :to => "movies#index"
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base

  belongs_to :movie

  validates :name, :presence => true, :uniqueness => { :scope => :movie_id }

  def search_instance
    @search ||= Twitter::Search.new
  end

  def prepare_params_for(page_number = 1)
    search_instance.clear
    search_instance.per_page(100).containing(name).page(page_number)
    add_since_to_search
  end

  def add_since_to_search
    if since_id
      search_instance.since(since_id)
    else
      search_instance.since_date(movie.released_on.to_s)
    end
  end

  def perform_search

    counter = 1

    while true

      output = prepare_params_for(counter).fetch

      create_tweets if output.results
      break unless search_instance.next_page?

      counter += 1
    end

    counter
  end

  def create_tweets
    transaction do
      valid_tweets.each { | tweet | movie.tweets << tweet }.tap do |tweets|
        tweets.size.nonzero? && update_attribute(:since_id, tweets.last.twitter_id)
      end
    end
  end

  def valid_tweets
    search_instance.map { | hashie | Tweet.from_hashie!(hashie) }.select(&:valid?)
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  # GET /keywords/new.xml
  def new
    @keyword = Keyword.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @keyword }
    end
  end

  # POST /keywords
  # POST /keywords.xml
  def create
    @movie    = Movie.find(params[:movie_id])
    @keyword  = @movie.keywords.build(params[:keyword])

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to(edit_movie_path(@movie), :notice => 'Keyword was successfully created.') }
        format.xml  { render :xml => @keyword, :status => :created, :location => @keyword }
      else
        format.html { redirect_to(@movie, :notice => 'Keyword was failed to created.') }
        format.xml  { render :xml => @keyword.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.xml
  def destroy
    @keyword = Keyword.find(params[:id])
    @keyword.destroy

    respond_to do |format|
      format.html { redirect_to(edit_movie_path(@keyword.movie)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keywords.each do |keyword| %>
  <tr>
    <td><%= keyword.name %></td>
    <td><%= link_to 'Show', keyword %></td>
    <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
    <td><%= link_to 'Destroy', keyword, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @keyword.name %>
</p>


<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>